// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTPkplT0ZHw6v2m-qS9cjBkNodLsWdry0',
    appId: '1:66742446932:web:5ebeb55e28331940a7f6c1',
    messagingSenderId: '66742446932',
    projectId: 'tracking-assgn',
    authDomain: 'tracking-assgn.firebaseapp.com',
    storageBucket: 'tracking-assgn.firebasestorage.app',
    measurementId: 'G-15B5RXF96D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZDhCTkcdHk-WQAEkh6oeqQEpSOSHN1N4',
    appId: '1:66742446932:android:30259f8f197e4fa3a7f6c1',
    messagingSenderId: '66742446932',
    projectId: 'tracking-assgn',
    storageBucket: 'tracking-assgn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd3ZjrBXnwaXo28PxWZGdnriPQ9KIIVws',
    appId: '1:66742446932:ios:530e2b0c2b359654a7f6c1',
    messagingSenderId: '66742446932',
    projectId: 'tracking-assgn',
    storageBucket: 'tracking-assgn.firebasestorage.app',
    iosBundleId: 'com.example.tracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd3ZjrBXnwaXo28PxWZGdnriPQ9KIIVws',
    appId: '1:66742446932:ios:530e2b0c2b359654a7f6c1',
    messagingSenderId: '66742446932',
    projectId: 'tracking-assgn',
    storageBucket: 'tracking-assgn.firebasestorage.app',
    iosBundleId: 'com.example.tracking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTPkplT0ZHw6v2m-qS9cjBkNodLsWdry0',
    appId: '1:66742446932:web:42d2a69d3f500b13a7f6c1',
    messagingSenderId: '66742446932',
    projectId: 'tracking-assgn',
    authDomain: 'tracking-assgn.firebaseapp.com',
    storageBucket: 'tracking-assgn.firebasestorage.app',
    measurementId: 'G-03R3KRB94R',
  );
}
